application: classtrip
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: bootstrap/css
- url: /fronts
  static_dir: bootstrap/fonts
- url: /js
  static_dir: bootstrap/js
- url: /.*
  script: _go_app
  login: required
  
- url: /admin/.*
  script: _go_app
  login: admin